"""
Stage 5: Weighted Hybrid Ensemble
Combines all 5 model outputs using a priori weights:
  - Rule-based:         0.20
  - TF-IDF LR:          0.20
  - TF-IDF GB:          0.20
  - BioClinicalBERT:    0.25
  - LLM:                0.15

Applied to both test set (benchmarking) and full 338k corpus (CVD labeling).
"""

import pandas as pd
import numpy as np
import os

# Test set probability files
TEST_TFIDF = "outputs/test_probas_tfidf.csv"
TEST_BERT = "outputs/test_probas_bert.csv"
TEST_RULE_PATH = "data/gold_standard_annotated.parquet"

# Full corpus probability files (generated by running each model on all 338k records)
FULL_RULE = "data/neiss2023_rule_based.parquet"
FULL_TFIDF_PROBA = "outputs/full_probas_tfidf.npy"
FULL_GB_PROBA = "outputs/full_probas_gb.npy"
FULL_BERT_PROBA = "outputs/full_probas_bert.npy"
LLM_EXTRACTED = "data/llm_extracted.parquet"

OUT_FULL = "data/neiss2023_ensemble_labels.parquet"
ENSEMBLE_THRESHOLD = 0.50

# A priori weights (paper Table 2)
WEIGHTS = {
    "rule": 0.20,
    "lr": 0.20,
    "gb": 0.20,
    "bert": 0.25,
    "llm": 0.15,
}

assert abs(sum(WEIGHTS.values()) - 1.0) < 1e-9, "Weights must sum to 1"


def weighted_ensemble(probas: dict, weights: dict) -> np.ndarray:
    """
    Compute weighted ensemble probability.
    probas: dict of model_name -> np.ndarray of probabilities (same length)
    weights: dict of model_name -> float weight
    """
    total = np.zeros(len(next(iter(probas.values()))))
    for key, w in weights.items():
        if key in probas:
            total += w * np.array(probas[key])
    return total


def evaluate_ensemble(ensemble_proba: np.ndarray, labels: np.ndarray,
                      threshold: float = 0.50) -> dict:
    """Evaluate ensemble on test set."""
    from sklearn.metrics import (
        roc_auc_score, average_precision_score,
        precision_score, recall_score, f1_score, confusion_matrix
    )

    preds = (ensemble_proba >= threshold).astype(int)
    auroc = roc_auc_score(labels, ensemble_proba)
    auprc = average_precision_score(labels, ensemble_proba)
    prec = precision_score(labels, preds, zero_division=0)
    rec = recall_score(labels, preds, zero_division=0)
    f1 = f1_score(labels, preds, zero_division=0)
    cm = confusion_matrix(labels, preds)

    print("\nHybrid Ensemble Test Performance (threshold=0.50):")
    print(f"  AUROC:     {auroc:.4f}")
    print(f"  AUPRC:     {auprc:.4f}")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall:    {rec:.4f}")
    print(f"  F1:        {f1:.4f}")
    print(f"  Confusion Matrix:\n{cm}")

    return {
        "model": "Hybrid Ensemble",
        "auroc": auroc, "auprc": auprc,
        "precision": prec, "recall": rec, "f1": f1,
        "threshold": threshold,
    }


def threshold_sensitivity(ensemble_proba: np.ndarray, labels: np.ndarray):
    """
    NLP decision threshold sensitivity analysis.
    Evaluates ensemble at thresholds 0.50, 0.80, 0.90 (paper Appendix).
    """
    from sklearn.metrics import precision_score, recall_score, f1_score
    print("\nThreshold Sensitivity Analysis:")
    print(f"{'Threshold':>12} {'Precision':>12} {'Recall':>10} {'F1':>8} {'N_Pos':>8}")
    for t in [0.50, 0.80, 0.90]:
        preds = (ensemble_proba >= t).astype(int)
        prec = precision_score(labels, preds, zero_division=0)
        rec = recall_score(labels, preds, zero_division=0)
        f1 = f1_score(labels, preds, zero_division=0)
        n_pos = preds.sum()
        print(f"{t:>12.2f} {prec:>12.4f} {rec:>10.4f} {f1:>8.4f} {n_pos:>8,}")


def run_test_set_ensemble():
    """Ensemble evaluation on 600-record held-out test set."""
    print("Loading test set probabilities...")

    tfidf_df = pd.read_csv(TEST_TFIDF)
    bert_df = pd.read_csv(TEST_BERT)

    # Merge on annotation_id
    merged = tfidf_df.merge(bert_df[["annotation_id", "proba_bert"]], on="annotation_id")

    # Rule-based: load from gold set
    gold = pd.read_parquet(TEST_RULE_PATH)
    test_gold = gold[gold["split"] == "test"][["annotation_id", "CVD_Rule_Label"]]
    merged = merged.merge(test_gold, on="annotation_id")
    merged["proba_rule"] = merged["CVD_Rule_Label"].astype(float)

    # LLM: for test records that overlap with rule-based positives
    if os.path.exists(LLM_EXTRACTED):
        llm_df = pd.read_parquet(LLM_EXTRACTED)
        llm_lookup = llm_df.set_index("CPSC_Case_Number")["proba_llm"].to_dict()
        # Map by case number if available
        if "CPSC_Case_Number" in merged.columns:
            merged["proba_llm"] = merged["CPSC_Case_Number"].map(llm_lookup).fillna(0.5)
        else:
            merged["proba_llm"] = 0.5  # neutral for non-LLM-processed records
    else:
        merged["proba_llm"] = merged["proba_rule"]  # fallback

    probas = {
        "rule": merged["proba_rule"].values,
        "lr": merged["proba_lr"].values,
        "gb": merged["proba_gb"].values,
        "bert": merged["proba_bert"].values,
        "llm": merged["proba_llm"].values,
    }

    ensemble_proba = weighted_ensemble(probas, WEIGHTS)
    labels = merged["gold_label"].values

    metrics = evaluate_ensemble(ensemble_proba, labels)
    threshold_sensitivity(ensemble_proba, labels)

    # Save
    merged["ensemble_proba"] = ensemble_proba
    merged["ensemble_label"] = (ensemble_proba >= ENSEMBLE_THRESHOLD).astype(int)
    merged.to_csv("outputs/test_ensemble_predictions.csv", index=False)
    print("\nTest ensemble predictions saved: outputs/test_ensemble_predictions.csv")

    return metrics


def apply_ensemble_to_full_corpus():
    """
    Apply ensemble to full 338,262 NEISS records.
    Requires pre-computed probability arrays from each model on the full corpus.
    """
    print("\nApplying ensemble to full corpus...")

    df = pd.read_parquet(FULL_RULE)
    n = len(df)

    # Rule-based
    proba_rule = df["CVD_Rule_Label"].astype(float).values

    # TF-IDF (load from saved numpy arrays if available)
    proba_lr = np.load(FULL_TFIDF_PROBA) if os.path.exists(FULL_TFIDF_PROBA) else proba_rule
    proba_gb = np.load(FULL_GB_PROBA) if os.path.exists(FULL_GB_PROBA) else proba_rule
    proba_bert = np.load(FULL_BERT_PROBA) if os.path.exists(FULL_BERT_PROBA) else proba_rule

    # LLM: only available for rule-based positives; default 0.5 for negatives
    proba_llm = np.full(n, 0.5)
    if os.path.exists(LLM_EXTRACTED):
        llm_df = pd.read_parquet(LLM_EXTRACTED)
        llm_lookup = dict(zip(
            llm_df["CPSC_Case_Number"].astype(str),
            llm_df["proba_llm"].values
        ))
        for i, case_no in enumerate(df["CPSC_Case_Number"].astype(str)):
            if case_no in llm_lookup:
                proba_llm[i] = llm_lookup[case_no]

    probas = {
        "rule": proba_rule, "lr": proba_lr,
        "gb": proba_gb, "bert": proba_bert, "llm": proba_llm
    }
    ensemble_proba = weighted_ensemble(probas, WEIGHTS)

    df["ensemble_proba"] = ensemble_proba
    df["CVD_Ensemble_Label"] = (ensemble_proba >= ENSEMBLE_THRESHOLD).astype(int)

    n_cvd = df["CVD_Ensemble_Label"].sum()
    print(f"\nFull corpus CVD positive (ensemble): {n_cvd:,} ({n_cvd/n*100:.2f}%)")

    # Survey-weighted prevalence
    if "Weight_Numeric" in df.columns:
        total_weight = df["Weight_Numeric"].sum()
        cvd_weight = df.loc[df["CVD_Ensemble_Label"] == 1, "Weight_Numeric"].sum()
        print(f"Weighted N (CVD positive): {cvd_weight:,.0f}")
        print(f"Weighted prevalence: {cvd_weight/total_weight*100:.2f}%")

    df.to_parquet(OUT_FULL, index=False)
    print(f"Full corpus ensemble labels saved: {OUT_FULL}")


def main():
    print("=" * 60)
    print("Stage 5: Weighted Hybrid Ensemble")
    print("=" * 60)
    print(f"Weights: {WEIGHTS}")

    os.makedirs("outputs", exist_ok=True)

    # Test set benchmarking
    if all(os.path.exists(p) for p in [TEST_TFIDF, TEST_BERT]):
        metrics = run_test_set_ensemble()
    else:
        print("Test probability files not found. Run stages 4 and 5 first.")

    # Full corpus
    if os.path.exists(FULL_RULE):
        apply_ensemble_to_full_corpus()


if __name__ == "__main__":
    main()
